language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

script:
  - npm run docs-build
after_script:
  - git init
  - git config user.name 'chaoming56'
  - git config user.email '1173306360@QQ.COM'
  - git add .
  - git commit -m '[ci skip] docs generate'
  - git push -f 'https://${GH_TOKEN}@github.com/gmfe/react-gm.git' master:master
