language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

script:
  - npm run docs-build
  - git add --all; git commit -m '[ci skip] docs generate'; git push -f 'https://${GH_TOKEN}@github.com/gmfe/react-gm.git' master:master
