const KEYBOARD_ONFOCUS = 'KEYBOARD_ONFOCUS_'
const KEYBOARD_DIRECTION = 'KEYBOARD_DIRECTION_'
const KEYBOARD_ENTER = 'KEYBOARD_ENTER_'
const KEYBOARD_TAB = 'KEYBOARD_TAB_'

export { KEYBOARD_ONFOCUS, KEYBOARD_DIRECTION, KEYBOARD_ENTER, KEYBOARD_TAB }
