const GMEVENT = 'GM_EVENT_'

const EVENT_TYPE = {
  DRAWER_SHOW: GMEVENT + 'DRAWER_SHOW',
  DRAWER_HIDE: GMEVENT + 'DRAWER_HIDE',
  MODAL_SHOW: GMEVENT + 'MODAL_SHOW',
  MODAL_HIDE: GMEVENT + 'MODAL_HIDE',
  DRAWER_SCROLL: GMEVENT + 'DRAWER_SCROLL',
  MODAL_SCROLL: GMEVENT + 'MODAL_SCROLL',
  BROWSER_SCROLL: GMEVENT + 'BROWSER_SCROLL',
  TABLE_SCROLL: GMEVENT + 'TABLE_SCROLL',
  FULL_LOADING_SHOW: GMEVENT + 'FULL_LOADING_SHOW',
  FULL_LOADING_HIDE: GMEVENT + 'FULL_LOADING_HIDE',
  TITLE_CHANGE: GMEVENT + 'TITLE_CHANGE'
}

export default EVENT_TYPE
